#***
_-$./""***
***...///"#"
#b_-$./""***["(https://sites.google.com/view/www-wytemike-w3spacaces-com/home"
    - name: Michael Glenn moneyman573 and BigGuy573 on Wiki
      url: "http://wiki.ubiquitous-network.ch/doku.php?id=en:devmon"
      about: Developing Devmon, Screenshots, ...
    - name: ✉ Devmon team 
      url: https://github.com/bonomani/devmon/discussions
      about: contact us
